FROM rocker/r-devel-ubsan-clang

RUN apt update && apt install --no-install-suggests -y libssl-dev

RUN RDscript --vanilla -e \
  'install.packages(c("Rcpp", "texreg"), repos = "https://cloud.r-project.org")'

CMD ["bash"]



