// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// new_defm
SEXP new_defm(const std::vector< int >& id, const IntegerMatrix& Y, const NumericMatrix& X, int order);
RcppExport SEXP _defm_new_defm(SEXP idSEXP, SEXP YSEXP, SEXP XSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::vector< int >& >::type id(idSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(new_defm(id, Y, X, order));
    return rcpp_result_gen;
END_RCPP
}
// init_defm
int init_defm(SEXP m);
RcppExport SEXP _defm_init_defm(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(init_defm(m));
    return rcpp_result_gen;
END_RCPP
}
// term_defm_ones
int term_defm_ones(SEXP m, int idx);
RcppExport SEXP _defm_term_defm_ones(SEXP mSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(term_defm_ones(m, idx));
    return rcpp_result_gen;
END_RCPP
}
// term_defm_fe
int term_defm_fe(SEXP m, int idx, double k);
RcppExport SEXP _defm_term_defm_fe(SEXP mSEXP, SEXP idxSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(term_defm_fe(m, idx, k));
    return rcpp_result_gen;
END_RCPP
}
// term_defm_transition
int term_defm_transition(SEXP m, std::vector< size_t > coords, int covar_idx);
RcppExport SEXP _defm_term_defm_transition(SEXP mSEXP, SEXP coordsSEXP, SEXP covar_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::vector< size_t > >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< int >::type covar_idx(covar_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(term_defm_transition(m, coords, covar_idx));
    return rcpp_result_gen;
END_RCPP
}
// print_defm
SEXP print_defm(SEXP x);
RcppExport SEXP _defm_print_defm(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(print_defm(x));
    return rcpp_result_gen;
END_RCPP
}
// loglike_defm
double loglike_defm(SEXP m, std::vector< double > par, bool as_log);
RcppExport SEXP _defm_loglike_defm(SEXP mSEXP, SEXP parSEXP, SEXP as_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::vector< double > >::type par(parSEXP);
    Rcpp::traits::input_parameter< bool >::type as_log(as_logSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_defm(m, par, as_log));
    return rcpp_result_gen;
END_RCPP
}
// sim_defm
IntegerMatrix sim_defm(SEXP m, std::vector< double > par);
RcppExport SEXP _defm_sim_defm(SEXP mSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::vector< double > >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_defm(m, par));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_defm_new_defm", (DL_FUNC) &_defm_new_defm, 4},
    {"_defm_init_defm", (DL_FUNC) &_defm_init_defm, 1},
    {"_defm_term_defm_ones", (DL_FUNC) &_defm_term_defm_ones, 2},
    {"_defm_term_defm_fe", (DL_FUNC) &_defm_term_defm_fe, 3},
    {"_defm_term_defm_transition", (DL_FUNC) &_defm_term_defm_transition, 3},
    {"_defm_print_defm", (DL_FUNC) &_defm_print_defm, 1},
    {"_defm_loglike_defm", (DL_FUNC) &_defm_loglike_defm, 3},
    {"_defm_sim_defm", (DL_FUNC) &_defm_sim_defm, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_defm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
