# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' New DEFM
#' @export
new_defm <- function(id, Y, X, order) {
    .Call(`_defm_new_defm`, id, Y, X, order)
}

#' @export
init_defm <- function(m) {
    invisible(.Call(`_defm_init_defm`, m))
}

#' @export
term_defm_ones <- function(m, idx = -1L) {
    invisible(.Call(`_defm_term_defm_ones`, m, idx))
}

#' @export
term_defm_fe <- function(m, idx = -1L, k = 1.0) {
    invisible(.Call(`_defm_term_defm_fe`, m, idx, k))
}

#' @export
term_defm_transition <- function(m, coords, covar_idx = -1L) {
    invisible(.Call(`_defm_term_defm_transition`, m, coords, covar_idx))
}

#' @export
print.DEFM <- function(x) {
    invisible(.Call(`_defm_print_defm`, x))
}

#' @export
loglike_defm <- function(m, par, as_log = TRUE) {
    .Call(`_defm_loglike_defm`, m, par, as_log)
}

